# What is Sudoku?
Sudoku is a puzzle in which players insert the numbers one to nine into a grid consisting of nine squares subdivided into a further nine smaller squares in such a way that every number appears once in each horizontal line, vertical line, and square.

In [ ]:
import sys
import numpy as np

In [18]:
# This code reads the input file given and builds a grid to be processed with it
f = open("../input.txt", "r")
lines = f.readlines()

#printing input files
print(lines)

['7 0 2 0 1 0 0 4 9\n', '1 0 0 2 0 0 0 0 0\n', '0 0 6 0 0 9 0 1 2\n', '0 0 3 8 0 0 4 0 0\n', '9 7 1 0 0 0 3 8 5\n', '0 0 4 0 0 3 2 0 0\n', '4 3 0 9 0 0 1 0 0\n', '0 0 0 0 0 8 0 0 7\n', '8 2 0 0 3 0 9 0 4']


In [19]:
# Creating a grid to hold content of text file
grid = []
for line in lines:
    intline = []
    sline = line.strip()
    cline = sline.replace(" ", "")
    for character in cline:
        intline.append(int(character))
    grid.append(intline)

#printing grid
print(grid)

[[7, 0, 2, 0, 1, 0, 0, 4, 9], [1, 0, 0, 2, 0, 0, 0, 0, 0], [0, 0, 6, 0, 0, 9, 0, 1, 2], [0, 0, 3, 8, 0, 0, 4, 0, 0], [9, 7, 1, 0, 0, 0, 3, 8, 5], [0, 0, 4, 0, 0, 3, 2, 0, 0], [4, 3, 0, 9, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 8, 0, 0, 7], [8, 2, 0, 0, 3, 0, 9, 0, 4]]


In [20]:
# function possible determines whether a given number can possibly go in a space
def possible(y,x,n):
  global grid
  # n is the number we want to fill in

  # 1st 
  # check if n already existed in vertical (y) axis
  # if exists, return False (not possible)
  for i in range(9):
    if grid[y][i] == n:
      return False

  # 2nd
  # check horizontal (x) axis
  for i in range(9):
    if grid[i][x] == n:
      return False

  # 3rd
  # check the 3x3 local grid
  x0 = (x//3)*3 
  y0 = (y//3)*3
  for i in range(3):
    for j in range(3):
      if grid[y0+i][x0+j] == n:
         return False

  # return true if pass all 3 checks.
  return True

In [21]:
# solve uses grid to iterate through every space and, if empty, try all possibilities for said space
def solve():
  global grid
  for y in range(9):
    for x in range(9):
      # Find blank positions in the grid (value = 0)
      if grid[y][x] == 0:
        # Loop n from 1-9
        for n in range(1,10):
          if possible(y,x,n):
            grid[y][x] = n
            solve()

            # This is where backtracking happens
            # Reset the latest position back to 0 and try with new n value
            grid[y][x] = 0
        return
  print(np.matrix(grid))

In [22]:
print("The sovled sudoku puzzle is:")
print("****************************")
solve()

The sovled sudoku puzzle is:
****************************
[[7 5 2 3 1 6 8 4 9]
 [1 9 8 2 7 4 6 5 3]
 [3 4 6 5 8 9 7 1 2]
 [2 6 3 8 5 7 4 9 1]
 [9 7 1 6 4 2 3 8 5]
 [5 8 4 1 9 3 2 7 6]
 [4 3 7 9 6 5 1 2 8]
 [6 1 9 4 2 8 5 3 7]
 [8 2 5 7 3 1 9 6 4]]
